### ISSUE TITLE
Change date format to yyyy-mm-dd.hr:mn:sc

### ISSUE THREAD

**Issue by moisseev** [ravenx99/backuppc-visualize#8]
I propose to change date format to yyyy-mm-dd.hr:mn:sc for internal time representation. It seems to me more clean and usable for scripting than mm-dd-yyyy.hr:mn:sc.
P.S. Proposed change will not affect date format in plots.

**Comment by ravenx99** [comment]
Resolved by f6864b8.  Anyone upgrading with existing plot files will have to fix the dates.
